services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: comments_app
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  app:
    build: 
      context: ./backend
    container_name: app
    restart: always
    ports:
      - '4000:4000'   # Changed to match your app's PORT in config.ts
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres  
      DB_NAME: comments_app
      REDIS_URL: redis://redis:6379 
      JWT_SECRET: token_top_secret
      PORT: 4000

volumes:
  postgres_data:
  redis_data: